#!/usr/bin/env zsh

curl -s -X 'GET' 'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,binancecoin,cardano,solana,polkadot,matic-network,monero,cosmos,oasis-network&vs_currencies=usd' -H 'accept: application/json' | jq -r 'keys[]
as $k | "\($k): \(.[$k] | .usd) USD\n"' | cowsay -f dragon-and-cow
